In [2]:
import numpy as np

In [6]:
#creating array
arr1 = np.array([1,2,3])   #-->1d
arr2 = np.array([[1,2,3],[4,5,6]])   #-->2d
print(arr1)
print()
print(arr2)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print()
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

(3,)
3
1

(2, 3)
6
2


In [12]:
#zeroes ones and random (weights /dummy data)

zeroes = np.zeros((3,2))
ones = np.ones((4,2))
random1 = np.random.rand(4,3)
random2 = np.random.rand(5,3)

print(zeroes)
print()
print(ones)
print()
print(random1)
print()
print(random2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[4.31217910e-02 5.56622978e-01 7.06280447e-01]
 [3.80924624e-01 3.50228939e-04 1.29497176e-01]
 [6.59476794e-02 4.56726187e-01 2.52834143e-01]
 [2.77010921e-01 2.78254502e-01 7.05708275e-01]]

[[0.91146151 0.76535452 0.99928912]
 [0.02960136 0.76952459 0.2410917 ]
 [0.29065691 0.74376167 0.89940816]
 [0.77897824 0.271302   0.10445916]
 [0.31320867 0.55914168 0.246191  ]]


In [22]:
# indexing and slicing (feature selection)
arr2[:,1]

array([2, 5])

In [24]:
#vectorized operations for fast ml
print(arr2 +2)
print(arr2 *2)
print(arr2 /2)

[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [25]:
#data scaling
print(np.mean(arr2))
print()
print(np.std(arr2))
print()
print(np.sum(arr2))

3.5

1.707825127659933

21


In [31]:
#reshaping the entrire array
old_arr = np.array([[5,4,3],[1,2,3]])
print(old_arr)
new_arr = old_arr.reshape(3,2)
print(new_arr)

[[5 4 3]
 [1 2 3]]
[[5 4]
 [3 1]
 [2 3]]


In [35]:
#dot product
X= np.array([[1,2,3],[4,5,6]])   #-->2d
Y= np.array([[1,2,3],[4,5]])   #-->2d
np.dot(X,Y)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.