In [2]:
import numpy as np

In [6]:
#creating array
arr1 = np.array([1,2,3])   #-->1d
arr2 = np.array([[1,2,3],[4,5,6]])   #-->2d
print(arr1)
print()
print(arr2)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print()
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

(3,)
3
1

(2, 3)
6
2


In [12]:
#zeroes ones and random (weights /dummy data)

zeroes = np.zeros((3,2))
ones = np.ones((4,2))
random1 = np.random.rand(4,3)
random2 = np.random.rand(5,3)

print(zeroes)
print()
print(ones)
print()
print(random1)
print()
print(random2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[4.31217910e-02 5.56622978e-01 7.06280447e-01]
 [3.80924624e-01 3.50228939e-04 1.29497176e-01]
 [6.59476794e-02 4.56726187e-01 2.52834143e-01]
 [2.77010921e-01 2.78254502e-01 7.05708275e-01]]

[[0.91146151 0.76535452 0.99928912]
 [0.02960136 0.76952459 0.2410917 ]
 [0.29065691 0.74376167 0.89940816]
 [0.77897824 0.271302   0.10445916]
 [0.31320867 0.55914168 0.246191  ]]


In [22]:
# indexing and slicing (feature selection)
arr2[:,1]

array([2, 5])